ConfigVersion:
#If ProtectTames is true, it will protect the tamed mobs of players from being damaged by players other than the owner.
ProtectTames: true
#If Allow Transfers is true, it will allow players with the appropriate permission to transfer their own tames.
AllowTransfers: true
#If AllowReleases is true, it will allow players with appropriate permission to release their own animals.
AllowReleases: true
#If ProtectHorses is true, players will not be able to ride another player's horse or open horse inventory.
ProtectHorses: true
#If AllowHorseDye is true, players will be able to manipulate the colors of their horses using Dye.
AllowHorseDye: true
#Toggling any of the Breeding Options to false will make it so players cannot breed that animal. (Tamed Animals Only)
Breeding:
  Horse: true
  Wolf: true
  Ocelot: true

messages:
    listener:
        animalDoesNotBelongToYou: '&cYou can't damage an animal that doesn't belong to you.'
        horseAlreadyOwned: 'This horse is already owned.'
        cantInteractWithHorse: '&cYou can't interact with a horse you do not own.'
        cantChangeStyle: 'You can't change the style on a horse that you do not own.'
        styleChanged: '&aHorse style changed.'
        cantChangeColor: '&cYou can't change the color of a horse you don't own.'
        colorChanged: '&aHorse color changed.'
        cantChangeVariant: '&cYou can't change the variant of a horse you don't own.'
        changedVariant: '&aHorse variation changed.'
        doesNotOwn: '&cYou do not own this animal.'
        animalReleased: '&aYou have released this animal to the wild.'
        animalTransfered: '&aYou have transferred this animal to %s'